#!/bin/bash
#
# SPDX-FileCopyrightText: 2023 AllWorldIT
#
# SPDX-License-Identifier: AGPL-3.0-or-later

set -eux

rm -rf build

meson setup build -Db_coverage=true -Db_werror=true -Dwith_tests=true

ninja -C build dist --verbose
