#!/bin/bash

set -eux

if [ ! -d build ]; then
	meson build -Db_coverage=true -Db_werror=true
fi

ninja -C build --verbose

meson test --wrap="valgrind --leak-check=full --show-leak-kinds=all" -C build --verbose --num-processes=1

ninja -C build coverage-html


