#!/bin/bash

set -eux

export CC=clang
export CXX=clang++

if [ ! -d build ]; then
	meson build -Db_coverage=true -Db_werror=true
fi

ninja -C build --verbose

meson test -C build --verbose --num-processes=1

ninja -C build coverage-html


