#!/bin/bash

set -eux

rm -rf build

meson build -Db_coverage=true -Db_werror=true -Dunit_testing=true --debug

ninja -C build --verbose

meson test --wrap="valgrind --leak-check=full --show-leak-kinds=all" -C build --verbose --num-processes=1

ninja -C build coverage-html


