
#ifndef COMMON_H
#define COMMON_H

#define STAP_BUFFER_COUNT 5000

#define STAP_MAX_PACKET_SIZE 9216

#define STAP_BUFFER_SIZE STAP_MAX_PACKET_SIZE + STAP_PACKET_HEADER_SIZE
// NK: For lack of any better value?
#define STAP_BUFFER_SIZE_COMPRESSION STAP_BUFFER_SIZE * 2

#define STAP_MAX_RECVMM_MESSAGES 1000

#define STAP_MIN_MSS_SIZE 1200
#define STAP_MAX_MSS_SIZE 9000

#define STAP_MIN_MTU_SIZE 1400	// FIXME: Change back to 1500
#define STAP_MAX_MTU_SIZE 9000

#endif